services:
  copy2z4z:
    build: .
    restart: always
    volumes:
      - ./songs:/root/songs
      - ./rclone.conf:/root/.config/rclone/rclone.conf
      - ./config.py:/app/config.py
    network_mode: bridge
